version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: "sqlite:///data.db"


#     depends_on:
#       - db
#     env_file:
#       - ./.env
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=myapp
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: